name: Build and deploy container app to Azure Web App - videoAI-angular

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry (ACR)
      uses: docker/login-action@v2
      with:
        registry: https://conainervideoai.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1207143ac93c49a695e924c2d13f4f74 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_79802cdc961b4221a397b9de56fe810f }}

    - name: Build and push container images using Docker Compose
      run: |
        docker-compose -f compose.yml build
        docker-compose -f compose.yml push

  deploy-angular:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-angular.outputs.webapp-url }}

    steps:
    - name: Deploy Angular App to Azure Web App
      id: deploy-angular
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'videoAI-angular'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_af792153d7324486bac2fa0c54253431 }}
        images: 'conainervideoai.azurecr.io/angularapp:1.0.0'

  deploy-flask:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-flask.outputs.webapp-url }}

    steps:
    - name: Deploy Flask App to Azure Web App
      id: deploy-flask
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'videoAI-flask'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_af792153d7324486bac2fa0c54253431 }}
        images: 'conainervideoai.azurecr.io/flaskapp:1.0.0'
